export const ROUTENAMES = {
    'MAINPAGE': 'MAINPAGE',
    'ACTIVITYSTREAM': 'ACTIVITYSTREAM',
    'LOGIN': 'LOGIN',
    'CONTACT': 'CONTACT',
    'ABOUT': 'ABOUT',
    'PROFILE': 'PROFILE',
    'PROFILE_VISIBILITY': 'PROFILE_VISIBILITY',
    'SOCIAL_MEDIA': 'SOCIAL_MEDIA',
    'REVIEWS': 'REVIEWS',
    'LISTING': 'LISTING',
    'LISTING_OVERVIEW': 'LISTING_OVERVIEW',
    'LISTING_DUPLICATES': 'LISTING_DUPLICATES',
    'LISTING_ANALYSIS': 'LISTING_ANALYSIS',
    'KUNDENANFRAGEN': 'KUNDENANFRAGEN',
    'CORRECTION_ADS': 'CORRECTION_ADS',
    'NOTIFICATIONS': 'NOTIFICATIONS',
    'TERMS_CONDITIONS': 'TERMS_CONDITIONS',
    'FAQ': 'FAQ',
    'AGB': 'AGB',
    'PRIVACY': 'PRIVACY',
    'PRIVACY_LONG': 'PRIVACY_LONG',
    'IMPRINT': 'IMPRINT',
    'TERMS_OF_USE': 'TERMS_OF_USE',
    'COOKIE_POLICY': 'COOKIE_POLICY',
    'ACCOUNT': 'ACCOUNT',
    'PERSONAL_DATA': 'PERSONAL_DATA',
    'FORGOT_PASSWORD': 'FORGOT_PASSWORD',
    'RESET_PASSWORD': 'RESET_PASSWORD',
    'CHANGE_PASSWORD': 'CHANGE_PASSWORD',
    'SUCCESS_PASSWORD_CHANGED': 'SUCCESS_PASSWORD_CHANGED',
    'LINK_SENT': 'LINK_SENT',
    'EDIT_URL': 'EDIT_URL',
    'ONBOARDING_ASSIGN_PASSWORD': 'ONBOARDING_ASSIGN_PASSWORD',
    'ONBOARDING_WELCOME': 'ONBOARDING_WELCOME',
    'ONBOARDING_BUSINESSINFO': 'ONBOARDING_BUSINESSINFO',
    'COMING_SOON': 'COMING_SOON',
    'PAGE_NOT_FOUND': 'PAGE_NOT_FOUND',
}

export const ROUTETITLES = {
    'MAINPAGE': 'Startseite', //Sellwerk
    'ACTIVITYSTREAM': 'Activitystream',
    'LOGIN': 'Login',
    'CONTACT': 'Kontakt',
    'ABOUT': 'Über uns',
    'PROFILE': 'Mein Profil',
    'PROFILE_VISIBILITY': 'Sichtbarkeit', // Profil-Sichtbarkeit
    'SOCIAL_MEDIA': 'Social-Media',
    'REVIEWS': 'Bewertungen',
    'LISTING': 'Online-Einträge',
    'LISTING_OVERVIEW': 'Übersicht',
    'LISTING_DUPLICATES': 'Duplikate',
    'LISTING_ANALYSIS': 'Auswertung',
    'KUNDENANFRAGEN': 'Kundenanfragen',
    'CORRECTION_ADS': 'Anzeigen',
    'NOTIFICATIONS': 'Benachrichtigungen',
    'TERMS_CONDITIONS': 'Terms & Conditions', // ?
    'FAQ': 'FAQ',
    'AGB': 'AGB',
    'PRIVACY': 'Datenschutz',
    'PRIVACY_LONG': 'Datenschutzerklärung', // not used in router
    'IMPRINT': 'Impressum',
    'TERMS_OF_USE': 'Nutzungsbedingungen',
    'COOKIE_POLICY': 'Cookie Bestimmungen',
    'ACCOUNT': 'Kontoeinstellungen', // Account
    'PERSONAL_DATA': 'Persönliche Daten',
    'FORGOT_PASSWORD': 'Passwort vergessen',
    'RESET_PASSWORD': 'Passwort zurücksetzen',
    'CHANGE_PASSWORD': 'Passwort ändern',
    'SUCCESS_PASSWORD_CHANGED': 'Passwort geändert',
    'LINK_SENT': 'Link gesendet',
    'EDIT_URL': 'URL anpassen',
    'ONBOARDING_ASSIGN_PASSWORD': 'Passwort vergeben',
    'ONBOARDING_WELCOME': 'Willkommen',
    'ONBOARDING_BUSINESSINFO': 'Firmendaten',
    'COMING_SOON': 'ComingSoon', // ?
    'PAGE_NOT_FOUND': 'PageNotFound', // ?
}